# Generated by Django 4.1.2 on 2022-12-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.CharField(default='weiss.jpg', max_length=300),
        ),
    ]
